defaults
auth           off
tls            off
logfile        /tmp/msmtp.log

account        mailpit
host           vwr_mailpit
port           1025
from           noreply@waitingRoOm.com

account default: mailpit